version: '3.8'
services:
  web:
    container_name: Appweb
    restart: always
    build: .
    ports:
      - "3000:3000"
  mongo:
    container_name: databaseCanchas
    image: mongo
    ports:
      - "27017:27017"
